name: Deploy frontend Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t vipinrajr/passwordgenerator-frontend  .
      - name: Publish Image to docker hub
        run: docker push vipinrajr/passwordgenerator-frontend:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull vipinrajr/passwordgenerator-frontend:latest 
      - name: Delete old container
        run: docker rm -f reactjs-app-container  
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name reactjs-app-container vipinrajr/passwordgenerator-frontend